# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/cpp_features.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/protobuf/cpp_features.proto',
  package='pb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"google/protobuf/cpp_features.proto\x12\x02pb\x1a google/protobuf/descriptor.proto\"M\n\x0b\x43ppFeatures\x12>\n\x12legacy_closed_enum\x18\x01 \x01(\x08\x42\"\x88\x01\x01\x98\x01\x04\x98\x01\x01\xa2\x01\t\x12\x04true\x18\xe6\x07\xa2\x01\n\x12\x05\x66\x61lse\x18\xe7\x07::\n\x03\x63pp\x12\x1b.google.protobuf.FeatureSet\x18\xe8\x07 \x01(\x0b\x32\x0f.pb.CppFeatures'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


CPP_FIELD_NUMBER = 1000
cpp = _descriptor.FieldDescriptor(
  name='cpp', full_name='pb.cpp', index=0,
  number=1000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_CPPFEATURES = _descriptor.Descriptor(
  name='CppFeatures',
  full_name='pb.CppFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='legacy_closed_enum', full_name='pb.CppFeatures.legacy_closed_enum', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\210\001\001\230\001\004\230\001\001\242\001\t\022\004true\030\346\007\242\001\n\022\005false\030\347\007', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['CppFeatures'] = _CPPFEATURES
DESCRIPTOR.extensions_by_name['cpp'] = cpp
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CppFeatures = _reflection.GeneratedProtocolMessageType('CppFeatures', (_message.Message,), {
  'DESCRIPTOR' : _CPPFEATURES,
  '__module__' : 'google.protobuf.cpp_features_pb2'
  # @@protoc_insertion_point(class_scope:pb.CppFeatures)
  })
_sym_db.RegisterMessage(CppFeatures)

cpp.message_type = _CPPFEATURES
google_dot_protobuf_dot_descriptor__pb2.FeatureSet.RegisterExtension(cpp)

_CPPFEATURES.fields_by_name['legacy_closed_enum']._options = None
# @@protoc_insertion_point(module_scope)
