# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/java_features.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/protobuf/java_features.proto',
  package='pb',
  syntax='proto2',
  serialized_options=b'\n\023com.google.protobufB\021JavaFeaturesProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#google/protobuf/java_features.proto\x12\x02pb\x1a google/protobuf/descriptor.proto\"\xea\x01\n\x0cJavaFeatures\x12>\n\x12legacy_closed_enum\x18\x01 \x01(\x08\x42\"\x88\x01\x01\x98\x01\x04\x98\x01\x01\xa2\x01\t\x12\x04true\x18\xe6\x07\xa2\x01\n\x12\x05\x66\x61lse\x18\xe7\x07\x12R\n\x0futf8_validation\x18\x02 \x01(\x0e\x32\x1f.pb.JavaFeatures.Utf8ValidationB\x18\x88\x01\x01\x98\x01\x04\x98\x01\x01\xa2\x01\x0c\x12\x07\x44\x45\x46\x41ULT\x18\xe6\x07\"F\n\x0eUtf8Validation\x12\x1b\n\x17UTF8_VALIDATION_UNKNOWN\x10\x00\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x01\x12\n\n\x06VERIFY\x10\x02:<\n\x04java\x12\x1b.google.protobuf.FeatureSet\x18\xe9\x07 \x01(\x0b\x32\x10.pb.JavaFeaturesB(\n\x13\x63om.google.protobufB\x11JavaFeaturesProto'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


JAVA_FIELD_NUMBER = 1001
java = _descriptor.FieldDescriptor(
  name='java', full_name='pb.java', index=0,
  number=1001, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

_JAVAFEATURES_UTF8VALIDATION = _descriptor.EnumDescriptor(
  name='Utf8Validation',
  full_name='pb.JavaFeatures.Utf8Validation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UTF8_VALIDATION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERIFY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_JAVAFEATURES_UTF8VALIDATION)


_JAVAFEATURES = _descriptor.Descriptor(
  name='JavaFeatures',
  full_name='pb.JavaFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='legacy_closed_enum', full_name='pb.JavaFeatures.legacy_closed_enum', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\210\001\001\230\001\004\230\001\001\242\001\t\022\004true\030\346\007\242\001\n\022\005false\030\347\007', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utf8_validation', full_name='pb.JavaFeatures.utf8_validation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\210\001\001\230\001\004\230\001\001\242\001\014\022\007DEFAULT\030\346\007', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JAVAFEATURES_UTF8VALIDATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=312,
)

_JAVAFEATURES.fields_by_name['utf8_validation'].enum_type = _JAVAFEATURES_UTF8VALIDATION
_JAVAFEATURES_UTF8VALIDATION.containing_type = _JAVAFEATURES
DESCRIPTOR.message_types_by_name['JavaFeatures'] = _JAVAFEATURES
DESCRIPTOR.extensions_by_name['java'] = java
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JavaFeatures = _reflection.GeneratedProtocolMessageType('JavaFeatures', (_message.Message,), {
  'DESCRIPTOR' : _JAVAFEATURES,
  '__module__' : 'google.protobuf.java_features_pb2'
  # @@protoc_insertion_point(class_scope:pb.JavaFeatures)
  })
_sym_db.RegisterMessage(JavaFeatures)

java.message_type = _JAVAFEATURES
google_dot_protobuf_dot_descriptor__pb2.FeatureSet.RegisterExtension(java)

DESCRIPTOR._options = None
_JAVAFEATURES.fields_by_name['legacy_closed_enum']._options = None
_JAVAFEATURES.fields_by_name['utf8_validation']._options = None
# @@protoc_insertion_point(module_scope)
