# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_protos.sharp_protos_out import edge_data_pb2 as edge__data__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EdgeDataServiceStub(object):
    """실시간 데이터 및 통계 데이터를 처리하는 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveSoitgaprdstats = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgaprdstats',
                request_serializer=edge__data__pb2.SoitgaprdstatsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgturntypestats = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgturntypestats',
                request_serializer=edge__data__pb2.SoitgturntypestatsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgkncrstats = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgkncrstats',
                request_serializer=edge__data__pb2.SoitgkncrstatsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitglanestats = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitglanestats',
                request_serializer=edge__data__pb2.SoitglanestatsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgcwdtinfo = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgcwdtinfo',
                request_serializer=edge__data__pb2.SoitgcwdtinfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgaprdqueu = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgaprdqueu',
                request_serializer=edge__data__pb2.SoitgaprdqueuRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitglanequeu = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitglanequeu',
                request_serializer=edge__data__pb2.SoitglanequeuRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgunacevet_S = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgunacevet_S',
                request_serializer=edge__data__pb2.Soitgunacevet_S_Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgunacevet_C = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgunacevet_C',
                request_serializer=edge__data__pb2.Soitgunacevet_C_Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgunacevet_E = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgunacevet_E',
                request_serializer=edge__data__pb2.Soitgunacevet_E_Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgrtmdtinfo_2K = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgrtmdtinfo_2K',
                request_serializer=edge__data__pb2.Soitgrtmdtinfo_2K_Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgenclsttsinfo = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgenclsttsinfo',
                request_serializer=edge__data__pb2.SoitgenclsttsinfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgcamrsttsinfo = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgcamrsttsinfo',
                request_serializer=edge__data__pb2.SoitgcamrsttsinfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgrtmdtinfo = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgrtmdtinfo',
                request_serializer=edge__data__pb2.SoitgrtmdtinfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveSoitgrtmdtinfo_4K = channel.unary_unary(
                '/edge.EdgeDataService/SaveSoitgrtmdtinfo_4K',
                request_serializer=edge__data__pb2.Soitgrtmdtinfo_4K_Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class EdgeDataServiceServicer(object):
    """실시간 데이터 및 통계 데이터를 처리하는 서비스 정의
    """

    def SaveSoitgaprdstats(self, request_iterator, context):
        """접근로별 통계 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgturntypestats(self, request_iterator, context):
        """회전별 통계 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgkncrstats(self, request_iterator, context):
        """차종별 통계 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitglanestats(self, request_iterator, context):
        """차로별 통계 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgcwdtinfo(self, request_iterator, context):
        """보행자 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgaprdqueu(self, request_iterator, context):
        """접근로별 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitglanequeu(self, request_iterator, context):
        """차로별 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgunacevet_S(self, request_iterator, context):
        """상황 발생 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgunacevet_C(self, request_iterator, context):
        """상황 진행중 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgunacevet_E(self, request_iterator, context):
        """상황 종료 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgrtmdtinfo_2K(self, request_iterator, context):
        """2K 실시간 차량검지 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgenclsttsinfo(self, request_iterator, context):
        """함체 상태 정보 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgcamrsttsinfo(self, request_iterator, context):
        """카메라 상태 정보 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgrtmdtinfo(self, request_iterator, context):
        """Merge 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSoitgrtmdtinfo_4K(self, request_iterator, context):
        """4K 실시간 차량검지 데이터를 수신하는 스트림 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveSoitgaprdstats': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgaprdstats,
                    request_deserializer=edge__data__pb2.SoitgaprdstatsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgturntypestats': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgturntypestats,
                    request_deserializer=edge__data__pb2.SoitgturntypestatsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgkncrstats': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgkncrstats,
                    request_deserializer=edge__data__pb2.SoitgkncrstatsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitglanestats': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitglanestats,
                    request_deserializer=edge__data__pb2.SoitglanestatsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgcwdtinfo': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgcwdtinfo,
                    request_deserializer=edge__data__pb2.SoitgcwdtinfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgaprdqueu': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgaprdqueu,
                    request_deserializer=edge__data__pb2.SoitgaprdqueuRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitglanequeu': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitglanequeu,
                    request_deserializer=edge__data__pb2.SoitglanequeuRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgunacevet_S': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgunacevet_S,
                    request_deserializer=edge__data__pb2.Soitgunacevet_S_Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgunacevet_C': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgunacevet_C,
                    request_deserializer=edge__data__pb2.Soitgunacevet_C_Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgunacevet_E': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgunacevet_E,
                    request_deserializer=edge__data__pb2.Soitgunacevet_E_Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgrtmdtinfo_2K': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgrtmdtinfo_2K,
                    request_deserializer=edge__data__pb2.Soitgrtmdtinfo_2K_Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgenclsttsinfo': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgenclsttsinfo,
                    request_deserializer=edge__data__pb2.SoitgenclsttsinfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgcamrsttsinfo': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgcamrsttsinfo,
                    request_deserializer=edge__data__pb2.SoitgcamrsttsinfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgrtmdtinfo': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgrtmdtinfo,
                    request_deserializer=edge__data__pb2.SoitgrtmdtinfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveSoitgrtmdtinfo_4K': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveSoitgrtmdtinfo_4K,
                    request_deserializer=edge__data__pb2.Soitgrtmdtinfo_4K_Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge.EdgeDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EdgeDataService(object):
    """실시간 데이터 및 통계 데이터를 처리하는 서비스 정의
    """

    @staticmethod
    def SaveSoitgaprdstats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgaprdstats',
            edge__data__pb2.SoitgaprdstatsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgturntypestats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgturntypestats',
            edge__data__pb2.SoitgturntypestatsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgkncrstats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgkncrstats',
            edge__data__pb2.SoitgkncrstatsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitglanestats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitglanestats',
            edge__data__pb2.SoitglanestatsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgcwdtinfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgcwdtinfo',
            edge__data__pb2.SoitgcwdtinfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgaprdqueu(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgaprdqueu',
            edge__data__pb2.SoitgaprdqueuRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitglanequeu(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitglanequeu',
            edge__data__pb2.SoitglanequeuRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgunacevet_S(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgunacevet_S',
            edge__data__pb2.Soitgunacevet_S_Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgunacevet_C(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgunacevet_C',
            edge__data__pb2.Soitgunacevet_C_Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgunacevet_E(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgunacevet_E',
            edge__data__pb2.Soitgunacevet_E_Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgrtmdtinfo_2K(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgrtmdtinfo_2K',
            edge__data__pb2.Soitgrtmdtinfo_2K_Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgenclsttsinfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgenclsttsinfo',
            edge__data__pb2.SoitgenclsttsinfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgcamrsttsinfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgcamrsttsinfo',
            edge__data__pb2.SoitgcamrsttsinfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgrtmdtinfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgrtmdtinfo',
            edge__data__pb2.SoitgrtmdtinfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSoitgrtmdtinfo_4K(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/edge.EdgeDataService/SaveSoitgrtmdtinfo_4K',
            edge__data__pb2.Soitgrtmdtinfo_4K_Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
