# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge_info_res.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65\x64ge_info_res.proto\x12\x04\x65\x64ge\"\xa4\x01\n\x0b\x45\x64geInfoRes\x12\x16\n\x0espot_camera_id\x18\x01 \x01(\t\x12\x1c\n\x14spot_intersection_id\x18\x02 \x01(\t\x12\'\n\x1f\x65\x63u_info_transmission_yes_or_no\x18\x03 \x01(\t\x12!\n\x19installed_location_number\x18\x04 \x01(\t\x12\x13\n\x0blane_offset\x18\x05 \x01(\x05\x42\x15\n\x13\x63om.middleware.grpcb\x06proto3')



_EDGEINFORES = DESCRIPTOR.message_types_by_name['EdgeInfoRes']
EdgeInfoRes = _reflection.GeneratedProtocolMessageType('EdgeInfoRes', (_message.Message,), {
  'DESCRIPTOR' : _EDGEINFORES,
  '__module__' : 'edge_info_res_pb2'
  # @@protoc_insertion_point(class_scope:edge.EdgeInfoRes)
  })
_sym_db.RegisterMessage(EdgeInfoRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.middleware.grpc'
  _EDGEINFORES._serialized_start=30
  _EDGEINFORES._serialized_end=194
# @@protoc_insertion_point(module_scope)
