# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_protos.java_protos_out import edge_info_res_pb2 as edge__info__res__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_protos.java_protos_out import ips_in_spot_res_pb2 as ips__in__spot__res__pb2
from grpc_protos.java_protos_out import spot_camera_id_res_pb2 as spot__camera__id__res__pb2


class EdgeInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSpotCameraId = channel.unary_unary(
                '/edge.EdgeInfoService/getSpotCameraId',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=spot__camera__id__res__pb2.SpotCameraIdRes.FromString,
                )
        self.getEdgeInfo = channel.unary_unary(
                '/edge.EdgeInfoService/getEdgeInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=edge__info__res__pb2.EdgeInfoRes.FromString,
                )
        self.getAllIpsInSpot = channel.unary_unary(
                '/edge.EdgeInfoService/getAllIpsInSpot',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ips__in__spot__res__pb2.IpsInSpotRes.FromString,
                )


class EdgeInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSpotCameraId(self, request, context):
        """Edge IP로 SPOT_CAMR_ID 찾기 (C++에서 조회)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getEdgeInfo(self, request, context):
        """Edge IP로 Edge 정보 찾기 (Python 코드 api_conn.py 에서 조회)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllIpsInSpot(self, request, context):
        """Edge IP로 Edge 정보 찾기 (Python 코드 statConstrol.py 에서 조회)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSpotCameraId': grpc.unary_unary_rpc_method_handler(
                    servicer.getSpotCameraId,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=spot__camera__id__res__pb2.SpotCameraIdRes.SerializeToString,
            ),
            'getEdgeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.getEdgeInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=edge__info__res__pb2.EdgeInfoRes.SerializeToString,
            ),
            'getAllIpsInSpot': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllIpsInSpot,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ips__in__spot__res__pb2.IpsInSpotRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge.EdgeInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EdgeInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSpotCameraId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edge.EdgeInfoService/getSpotCameraId',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            spot__camera__id__res__pb2.SpotCameraIdRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getEdgeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edge.EdgeInfoService/getEdgeInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            edge__info__res__pb2.EdgeInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllIpsInSpot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edge.EdgeInfoService/getAllIpsInSpot',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ips__in__spot__res__pb2.IpsInSpotRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
