# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge_info_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_protos.java_protos_out import spot_camera_id_res_pb2 as spot__camera__id__res__pb2
from grpc_protos.java_protos_out import edge_info_res_pb2 as edge__info__res__pb2
from grpc_protos.java_protos_out import ips_in_spot_res_pb2 as ips__in__spot__res__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65\x64ge_info_service.proto\x12\x04\x65\x64ge\x1a\x18spot_camera_id_res.proto\x1a\x13\x65\x64ge_info_res.proto\x1a\x15ips_in_spot_res.proto\x1a\x1bgoogle/protobuf/empty.proto2\xcc\x01\n\x0f\x45\x64geInfoService\x12@\n\x0fgetSpotCameraId\x12\x16.google.protobuf.Empty\x1a\x15.edge.SpotCameraIdRes\x12\x38\n\x0bgetEdgeInfo\x12\x16.google.protobuf.Empty\x1a\x11.edge.EdgeInfoRes\x12=\n\x0fgetAllIpsInSpot\x12\x16.google.protobuf.Empty\x1a\x12.edge.IpsInSpotResB$\n\x13\x63om.middleware.grpcB\rEdgeInfoProtob\x06proto3')



_EDGEINFOSERVICE = DESCRIPTOR.services_by_name['EdgeInfoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.middleware.grpcB\rEdgeInfoProto'
  _EDGEINFOSERVICE._serialized_start=133
  _EDGEINFOSERVICE._serialized_end=337
# @@protoc_insertion_point(module_scope)
