# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ips_in_spot_res.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ips_in_spot_res.proto\x12\x04\x65\x64ge\"b\n\x0cIpsInSpotRes\x12\x14\n\x0c\x63\x61mera_2k_ip\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61mera_4k_ip\x18\x02 \x01(\t\x12\x12\n\nedge_2k_ip\x18\x03 \x01(\t\x12\x12\n\nedge_4k_ip\x18\x04 \x01(\tb\x06proto3')



_IPSINSPOTRES = DESCRIPTOR.message_types_by_name['IpsInSpotRes']
IpsInSpotRes = _reflection.GeneratedProtocolMessageType('IpsInSpotRes', (_message.Message,), {
  'DESCRIPTOR' : _IPSINSPOTRES,
  '__module__' : 'ips_in_spot_res_pb2'
  # @@protoc_insertion_point(class_scope:edge.IpsInSpotRes)
  })
_sym_db.RegisterMessage(IpsInSpotRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IPSINSPOTRES._serialized_start=31
  _IPSINSPOTRES._serialized_end=129
# @@protoc_insertion_point(module_scope)
