# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spot_camera_id_res.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18spot_camera_id_res.proto\x12\x04\x65\x64ge\")\n\x0fSpotCameraIdRes\x12\x16\n\x0espot_camera_id\x18\x01 \x01(\tb\x06proto3')



_SPOTCAMERAIDRES = DESCRIPTOR.message_types_by_name['SpotCameraIdRes']
SpotCameraIdRes = _reflection.GeneratedProtocolMessageType('SpotCameraIdRes', (_message.Message,), {
  'DESCRIPTOR' : _SPOTCAMERAIDRES,
  '__module__' : 'spot_camera_id_res_pb2'
  # @@protoc_insertion_point(class_scope:edge.SpotCameraIdRes)
  })
_sym_db.RegisterMessage(SpotCameraIdRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPOTCAMERAIDRES._serialized_start=34
  _SPOTCAMERAIDRES._serialized_end=75
# @@protoc_insertion_point(module_scope)
