# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_protos.java_protos_out import traffic_signal_res_pb2 as traffic__signal__res__pb2


class TrafficSignalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnTrafficSignalChange = channel.unary_stream(
                '/signal.TrafficSignalService/OnTrafficSignalChange',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=traffic__signal__res__pb2.TrafficSignalRes.FromString,
                )


class TrafficSignalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnTrafficSignalChange(self, request, context):
        """신호 정보 변경시 해당되는 Edge에 전송하는 메서드
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficSignalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnTrafficSignalChange': grpc.unary_stream_rpc_method_handler(
                    servicer.OnTrafficSignalChange,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=traffic__signal__res__pb2.TrafficSignalRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signal.TrafficSignalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrafficSignalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnTrafficSignalChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/signal.TrafficSignalService/OnTrafficSignalChange',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            traffic__signal__res__pb2.TrafficSignalRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
