# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic_signal_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_protos.java_protos_out import traffic_signal_res_pb2 as traffic__signal__res__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctraffic_signal_service.proto\x12\x06signal\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18traffic_signal_res.proto2c\n\x14TrafficSignalService\x12K\n\x15OnTrafficSignalChange\x12\x16.google.protobuf.Empty\x1a\x18.signal.TrafficSignalRes0\x01\x62\x06proto3')



_TRAFFICSIGNALSERVICE = DESCRIPTOR.services_by_name['TrafficSignalService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAFFICSIGNALSERVICE._serialized_start=95
  _TRAFFICSIGNALSERVICE._serialized_end=194
# @@protoc_insertion_point(module_scope)
