# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic_signal_res.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18traffic_signal_res.proto\x12\x06signal\"o\n\x10TrafficSignalRes\x12\x1e\n\x16\x61_ring_movement_number\x18\x01 \x01(\x05\x12\x1e\n\x16\x62_ring_movement_number\x18\x02 \x01(\x05\x12\x1b\n\x13\x63ollected_unix_time\x18\x03 \x01(\x03\x62\x06proto3')



_TRAFFICSIGNALRES = DESCRIPTOR.message_types_by_name['TrafficSignalRes']
TrafficSignalRes = _reflection.GeneratedProtocolMessageType('TrafficSignalRes', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALRES,
  '__module__' : 'traffic_signal_res_pb2'
  # @@protoc_insertion_point(class_scope:signal.TrafficSignalRes)
  })
_sym_db.RegisterMessage(TrafficSignalRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAFFICSIGNALRES._serialized_start=36
  _TRAFFICSIGNALRES._serialized_end=147
# @@protoc_insertion_point(module_scope)
