# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/cpp_features.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"google/protobuf/cpp_features.proto\x12\x02pb\x1a google/protobuf/descriptor.proto\"M\n\x0b\x43ppFeatures\x12>\n\x12legacy_closed_enum\x18\x01 \x01(\x08\x42\"\x88\x01\x01\x98\x01\x04\x98\x01\x01\xa2\x01\t\x12\x04true\x18\xe6\x07\xa2\x01\n\x12\x05\x66\x61lse\x18\xe7\x07::\n\x03\x63pp\x12\x1b.google.protobuf.FeatureSet\x18\xe8\x07 \x01(\x0b\x32\x0f.pb.CppFeatures')


CPP_FIELD_NUMBER = 1000
cpp = DESCRIPTOR.extensions_by_name['cpp']

_CPPFEATURES = DESCRIPTOR.message_types_by_name['CppFeatures']
CppFeatures = _reflection.GeneratedProtocolMessageType('CppFeatures', (_message.Message,), {
  'DESCRIPTOR' : _CPPFEATURES,
  '__module__' : 'google.protobuf.cpp_features_pb2'
  # @@protoc_insertion_point(class_scope:pb.CppFeatures)
  })
_sym_db.RegisterMessage(CppFeatures)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FeatureSet.RegisterExtension(cpp)

  DESCRIPTOR._options = None
  _CPPFEATURES.fields_by_name['legacy_closed_enum']._options = None
  _CPPFEATURES.fields_by_name['legacy_closed_enum']._serialized_options = b'\210\001\001\230\001\004\230\001\001\242\001\t\022\004true\030\346\007\242\001\n\022\005false\030\347\007'
  _CPPFEATURES._serialized_start=76
  _CPPFEATURES._serialized_end=153
# @@protoc_insertion_point(module_scope)
